### ISSUE TITLE
Can't get sample to work

### ISSUE THREAD

**Issue by AnderssonPeter** [peterstark72/py-skanetrafiken#1]
Hi i'm totally new to Python.
I tried you example on Python 3 (this is the one im going to be using in the end)
https://repl.it/G347/0
```bash
Traceback (most recent call last):
  File "python", line 1, in <module>
  File "/goval_modules/python35/skanetrafiken.py", line 260
    print querystation(u"Tygelsjö")
                     ^
SyntaxError: invalid syntax
```

And i tried on Python 2
https://repl.it/G34k/0
```bash
Traceback (most recent call last):
  File "python", line 1, in <module>
ImportError: No module named lxml
```
I installed the lxml package but i still get the same error

**Comment by AnderssonPeter** [comment]
Also while trying to install it on my local machine i got the following errors:
```bash
pip3 install skanetrafiken
Collecting skanetrafiken
  Downloading skanetrafiken-2.0.1.tar.gz
Collecting lxml (from skanetrafiken)
  Downloading lxml-3.7.3-cp36-cp36m-win32.whl (2.9MB)
    100% |████████████████████████████████| 2.9MB 451kB/s
Installing collected packages: lxml, skanetrafiken
  Running setup.py install for skanetrafiken ... error
Exception:
Traceback (most recent call last):
  File "...\appdata\local\programs\python\python36-32\lib\site-packages\pip\compat\__init__.py", line 73, in console_to_str
    return s.decode(sys.__stdout__.encoding)
UnicodeDecodeError: 'utf-8' codec can't decode byte 0xf6 in position 32: invalid start byte

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "...\appdata\local\programs\python\python36-32\lib\site-packages\pip\basecommand.py", line 215, in main
    status = self.run(options, args)
  File "...\appdata\local\programs\python\python36-32\lib\site-packages\pip\commands\install.py", line 342, in run
    prefix=options.prefix_path,
  File "...\appdata\local\programs\python\python36-32\lib\site-packages\pip\req\req_set.py", line 784, in install
    **kwargs
  File "...\appdata\local\programs\python\python36-32\lib\site-packages\pip\req\req_install.py", line 878, in install
    spinner=spinner,
  File "...\appdata\local\programs\python\python36-32\lib\site-packages\pip\utils\__init__.py", line 676, in call_subprocess
    line = console_to_str(proc.stdout.readline())
  File "...\appdata\local\programs\python\python36-32\lib\site-packages\pip\compat\__init__.py", line 75, in console_to_str
    return s.decode('utf_8')
UnicodeDecodeError: 'utf-8' codec can't decode byte 0xf6 in position 32: invalid start byte
```

**Comment by peterstark72** [comment]
Hi, it's not made for Python3. Let me try and fix that real quick. I make an update tonight. 

The "lxml" problem I don't know.

**Comment by peterstark72** [comment]
Hi, try now with Python 3 
`pip install skanetrafiken --upgrade`

This should work

```
import skanetrafiken as sk
sk.querystation("Malmö C")
sk.resultspage("Malmö C|80000|0", "landskrona|82000|0")

```

**Comment by AnderssonPeter** [comment]
@peterstark72 Thanks that did the trick!
Two last questions:
* My guess is that `Malmö C|80000|0` = `Station Name|ID|???` but what is the last number?
* How do i send NoOf?
  Looking at http://labs.skanetrafiken.se/v2.2/GetJourney.xsd and your `tests.py` i managed to figure out the following: `sk.resultspage(selPointFr="Sölvesborg resecentrum|10001|0", selPointTo="Kristianstad C|90042|0", cmdAction="search", inpTime="07:28")` but if i add `, NoOf="1"` i get the following error:
```bash
Traceback (most recent call last):
  File "<stdin>", line 1, in <module>
TypeError: resultspage() got an unexpected keyword argument 'NoOf'
```

**Comment by peterstark72** [comment]
I think the last number indicates what kind of point it is, e.g. Stop Area or Point of Interest. Check Skånetrafiken API documentation. 

I missed NoOf. There is a new version 2.1.2 out now with that attribute.

**Comment by AnderssonPeter** [comment]
It seems there is no information about delays and cancellations?
The train today `sk.resultspage(selPointFr="Ystads station|86239|0", selPointTo="Simrishamns station|91069|0", inpTime="08:56")` was cancelled but there is no information about it in the result? (if there is no way to get cancellations and delays i can't solve my problem, if that is the case sorry for wasting your time..)

**Comment by peterstark72** [comment]
You get delays as RealTimeInfo from StationResults, but I am not sure about cancellations. 

http://www.labs.skanetrafiken.se/v2.2/stationresults.asp?selPointFrKey=86239&inpTime=08:50&inpDate=20170321

**Comment by AnderssonPeter** [comment]
@peterstark72 Thanks!
